#! /usr/bin/env python
import sys
import os
import generateMenuFromJSON
out_dir    = sys.argv[1]
os.system(f"mkdir -p {out_dir}")
data_dir   = '../data'
menus      = [ menu for menu in os.listdir(data_dir) if menu.endswith('.json') ]
evtModes   = ["OnSpill", "OffSpill", "all"]
for m in menus:
    for evt in evtModes:
        menu_file  = '../data/{}'.format(m)
        generateMenuFromJSON.generate(menu_file,
                                      evt,
                                      out_dir,
                                      False )
