name: Build Single Pkg Workflow

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:

  build_single_pkg:
    name: build single pkg
    uses: Mu2e/.github/.github/workflows/mu2e-build-single-pkg.yml@stable
